# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DMMacUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DMMacUI
  pod 'Masonry', '~> 1.0.2'
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

end
